### ISSUE TITLE
1.2.3 始终报错，求帮助

### ISSUE THREAD

**Issue by yangdq1** [abel533/mapper-boot-starter#10]
HI，大神，1.2.0碰到类似问题，1.2.1解决后，升级到1.2.3又出现了，看升级文档从1.2.1 到 1.2.3好像不需要改什么内容，求帮助，我遗漏了什么么？

Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.ConditionProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 150 common frames omitted

**Comment by abel533** [comment]
配置 mappers 参数。

**Comment by yangdq1** [comment]
呃，是指哪个参数？
