### ISSUE TITLE
升级到1.2.4版本发现问题

### ISSUE THREAD

**Issue by leechor** [abel533/mapper-boot-starter#12]
```
2018-03-12 19:19:13.111 [http-nio-8090-exec-2] DEBUG com.boot.mgt.dao.TaMapper.selectOne - ==>  Preparing: SELECT id,number,name,password,is_on_duty,add_time,level FROM ta WHERE number = ? 
2018-03-12 19:19:13.111 [http-nio-8090-exec-2] DEBUG com.boot.mgt.dao.TaMapper.selectOne - ==> Parameters: 4321(String)
2018-03-12 19:19:13.113 [http-nio-8090-exec-2] DEBUG com.boot.mgt.dao.TaMapper.selectOne - <==      Total: 1
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.ExampleProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.ExampleProvider
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy82.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy92.selectByExample(Unknown Source)
	at com.boot.mgt.service.impl.TaAccidentServiceImpl.list(TaAccidentServiceImpl.kt:55)
	at com.boot.mgt.controller.web.TaAccidentController.list(TaAccidentController.kt:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.ExampleProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.ExampleProvider
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:135)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.getBoundSql(ProviderSqlSource.java:103)
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:83)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy109.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 57 more
Caused by: java.lang.InstantiationException: tk.mybatis.mapper.provider.ExampleProvider
	at java.lang.Class.newInstance(Class.java:427)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:117)
	... 69 more
Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.ExampleProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 70 more
```

1.2.3没有发现这个问题。

**Comment by abel533** [comment]
具体调用哪个方法报的错？能不能贴出来看看？

**Comment by leechor** [comment]
在使用Example时，val list = accidentMapper.selectByExample(example),2.0.0-beta3也没有这个问题.(kotlin)

**Comment by abel533** [comment]
```
2018-03-12 21:12:10.592 DEBUG 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : ==>  Preparing: SELECT Id,countryname,countrycode FROM country LIMIT ? 
2018-03-12 21:12:10.592 DEBUG 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : ==> Parameters: 10(Integer)
2018-03-12 21:12:10.593 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==    Columns: Id, countryname, countrycode
2018-03-12 21:12:10.594 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 10, Australia, AU
2018-03-12 21:12:10.594 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 11, Austria, AT
2018-03-12 21:12:10.595 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 12, Azerbaijan, AZ
2018-03-12 21:12:10.595 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 13, Bahamas, BS
2018-03-12 21:12:10.595 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 14, Bahrain, BH
2018-03-12 21:12:10.595 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 15, Bangladesh, BD
2018-03-12 21:12:10.595 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 16, Barbados, BB
2018-03-12 21:12:10.596 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 17, Belarus, BY
2018-03-12 21:12:10.596 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 18, Belgium, BE
2018-03-12 21:12:10.596 TRACE 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==        Row: 19, Belize, BZ
2018-03-12 21:12:10.596 DEBUG 18140 --- [nio-9090-exec-2] t.m.s.m.CountryMapper.selectByExample    : <==      Total: 10
```
复现不了。。

你在 https://github.com/abel533/MyBatis-Spring-Boot 这个项目上试试。
